-- Watchtower ML Scored Tables
-- Run in the Supabase SQL Editor AFTER creating these tables.
-- Scores are batch-written by the ml-pipelines notebooks and read
-- by the portal UI via useSupabaseQuery.

-- ---------------------------------------------------------------------------
-- 1. donor_upgrade_scores
--    Populated by: ml-pipelines/04_donor_upgrade_predictor/
--    Read by: /portal/donors (DonorsContributionsPage)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.donor_upgrade_scores (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  supporter_id        integer NOT NULL REFERENCES public.supporters(supporter_id) ON DELETE CASCADE,
  score               numeric(6, 4) NOT NULL,        -- predict_proba value 0.0–1.0
  band                text NOT NULL                  -- 'High' | 'Medium' | 'Low'
    CHECK (band IN ('High', 'Medium', 'Low')),
  recommended_action  text,                          -- plain-language staff suggestion
  model_version       text NOT NULL DEFAULT '1.0',
  scored_at           timestamptz NOT NULL DEFAULT now(),
  UNIQUE (supporter_id)                              -- one active score per supporter
);

-- RLS: staff/admin can read; only service-role (notebook export) can write.
ALTER TABLE public.donor_upgrade_scores ENABLE ROW LEVEL SECURITY;

CREATE POLICY "staff_read_donor_upgrade_scores"
  ON public.donor_upgrade_scores
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.user_roles ur
      WHERE ur.user_id = auth.uid()
        AND ur.role_id IN (3, 4)  -- staff=3, admin=4
    )
  );

-- ---------------------------------------------------------------------------
-- 2. donor_churn_scores
--    Populated by: ml-pipelines/donor-churn-prediction.ipynb
--    Read by: /portal/donors (DonorsContributionsPage, Top Donors table)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.donor_churn_scores (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  supporter_id    integer NOT NULL REFERENCES public.supporters(supporter_id) ON DELETE CASCADE,
  churn_prob      numeric(6, 4),                     -- predict_proba lapse probability
  churn_risk_band text NOT NULL                      -- 'High' | 'Medium' | 'Low'
    CHECK (churn_risk_band IN ('High', 'Medium', 'Low')),
  model_version   text NOT NULL DEFAULT '1.0',
  scored_at       timestamptz NOT NULL DEFAULT now(),
  UNIQUE (supporter_id)
);

ALTER TABLE public.donor_churn_scores ENABLE ROW LEVEL SECURITY;

CREATE POLICY "staff_read_donor_churn_scores"
  ON public.donor_churn_scores
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.user_roles ur
      WHERE ur.user_id = auth.uid()
        AND ur.role_id IN (3, 4)
    )
  );

-- ---------------------------------------------------------------------------
-- 3. resident_ml_scores
--    Populated by: ml-pipelines/reintegration-readiness.ipynb,
--                  ml-pipelines/school-struggle-risk.ipynb,
--                  ml-pipelines/resident-wellbeing-prediction.ipynb,
--                  ml-pipelines/02_incident_leading_indicators/
--    Read by: /portal/caseload (CaseloadPage)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.resident_ml_scores (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resident_id             integer NOT NULL,          -- FK to residents table
  reintegration_band      text                       -- 'Ready' | 'Approaching' | 'Not Ready' | null
    CHECK (reintegration_band IN ('Ready', 'Approaching', 'Not Ready') OR reintegration_band IS NULL),
  reintegration_score     numeric(6, 4),
  school_struggle_band    text
    CHECK (school_struggle_band IN ('High', 'Medium', 'Low') OR school_struggle_band IS NULL),
  school_struggle_score   numeric(6, 4),
  wellbeing_band          text
    CHECK (wellbeing_band IN ('High', 'Medium', 'Low') OR wellbeing_band IS NULL),
  wellbeing_score         numeric(6, 4),
  incident_risk_band      text
    CHECK (incident_risk_band IN ('High', 'Medium', 'Low') OR incident_risk_band IS NULL),
  incident_risk_score     numeric(6, 4),
  model_version           text NOT NULL DEFAULT '1.0',
  scored_at               timestamptz NOT NULL DEFAULT now(),
  UNIQUE (resident_id)
);

ALTER TABLE public.resident_ml_scores ENABLE ROW LEVEL SECURITY;

CREATE POLICY "staff_read_resident_ml_scores"
  ON public.resident_ml_scores
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.user_roles ur
      WHERE ur.user_id = auth.uid()
        AND ur.role_id IN (3, 4)
    )
  );

-- ---------------------------------------------------------------------------
-- 4. safehouse_ml_scores
--    Populated by: ml-pipelines/03_safehouse_value_add/
--    Read by: /portal/reports (ReportsPage, staff/admin only)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.safehouse_ml_scores (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  safehouse_id        integer NOT NULL,
  safehouse_name      text,
  value_add_coef      numeric(8, 4),
  avg_outcome_change  numeric(8, 4),
  resident_count      integer,
  model_version       text NOT NULL DEFAULT '1.0',
  scored_at           timestamptz NOT NULL DEFAULT now(),
  UNIQUE (safehouse_id)
);

ALTER TABLE public.safehouse_ml_scores ENABLE ROW LEVEL SECURITY;

CREATE POLICY "staff_read_safehouse_ml_scores"
  ON public.safehouse_ml_scores
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.user_roles ur
      WHERE ur.user_id = auth.uid()
        AND ur.role_id IN (3, 4)
    )
  );

-- ---------------------------------------------------------------------------
-- 5. social_media_ml_scores
--    Populated by: ml-pipelines/social-media-optimization.ipynb
--    Read by: /portal/reports (ReportsPage, social_media_rep and above)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.social_media_ml_scores (
  id                            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id                       integer,
  platform                      text,
  content_type                  text,
  predicted_engagement_rate     numeric(8, 4),
  predicted_donation_referrals  numeric(8, 2),
  recommendation                text,
  model_version                 text NOT NULL DEFAULT '1.0',
  scored_at                     timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.social_media_ml_scores ENABLE ROW LEVEL SECURITY;

CREATE POLICY "social_rep_read_social_ml_scores"
  ON public.social_media_ml_scores
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.user_roles ur
      WHERE ur.user_id = auth.uid()
        AND ur.role_id IN (1, 3, 4)  -- social_media_rep=1, staff=3, admin=4
    )
  );

-- ---------------------------------------------------------------------------
-- Notes for notebook authors
-- ---------------------------------------------------------------------------
-- To write scores from Python (service role key required):
--   from supabase import create_client
--   client = create_client(SUPABASE_URL, SUPABASE_SERVICE_KEY)
--   client.table('donor_upgrade_scores').upsert(rows, on_conflict='supporter_id').execute()
--
-- The UNIQUE constraint on supporter_id enables upsert (ON CONFLICT DO UPDATE)
-- so re-running the notebook refreshes scores without duplicates.
