-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.donation_allocations (
  allocation_id integer NOT NULL,
  donation_id integer,
  safehouse_id integer,
  program_area text,
  amount_allocated numeric,
  allocation_date date,
  allocation_notes text,
  CONSTRAINT donation_allocations_pkey PRIMARY KEY (allocation_id),
  CONSTRAINT donation_allocations_donation_id_fkey FOREIGN KEY (donation_id) REFERENCES public.donations(donation_id),
  CONSTRAINT donation_allocations_safehouse_id_fkey FOREIGN KEY (safehouse_id) REFERENCES public.safehouses(safehouse_id)
);
CREATE TABLE public.donations (
  donation_id integer NOT NULL,
  supporter_id integer,
  donation_type text,
  donation_date date,
  is_recurring boolean DEFAULT false,
  campaign_name text,
  channel_source text,
  currency_code text,
  amount numeric,
  estimated_value numeric,
  impact_unit text,
  notes text,
  referral_post_id integer,
  CONSTRAINT donations_pkey PRIMARY KEY (donation_id),
  CONSTRAINT donations_supporter_id_fkey FOREIGN KEY (supporter_id) REFERENCES public.supporters(supporter_id)
);
CREATE TABLE public.donor_churn_scores (
  score_id integer NOT NULL DEFAULT nextval('donor_churn_scores_score_id_seq'::regclass),
  supporter_id integer,
  scored_at timestamp with time zone DEFAULT now(),
  churn_risk_score numeric,
  risk_tier text,
  CONSTRAINT donor_churn_scores_pkey PRIMARY KEY (score_id),
  CONSTRAINT donor_churn_scores_supporter_id_fkey FOREIGN KEY (supporter_id) REFERENCES public.supporters(supporter_id)
);
CREATE TABLE public.education_records (
  education_record_id integer NOT NULL,
  resident_id integer,
  record_date date,
  education_level text,
  school_name text,
  enrollment_status text,
  attendance_rate numeric,
  progress_percent numeric,
  completion_status text,
  notes text,
  CONSTRAINT education_records_pkey PRIMARY KEY (education_record_id),
  CONSTRAINT education_records_resident_id_fkey FOREIGN KEY (resident_id) REFERENCES public.residents(resident_id)
);
CREATE TABLE public.health_wellbeing_records (
  health_record_id integer NOT NULL,
  resident_id integer,
  record_date date,
  general_health_score numeric,
  nutrition_score numeric,
  sleep_quality_score numeric,
  energy_level_score numeric,
  height_cm numeric,
  weight_kg numeric,
  bmi numeric,
  medical_checkup_done boolean DEFAULT false,
  dental_checkup_done boolean DEFAULT false,
  psychological_checkup_done boolean DEFAULT false,
  notes text,
  CONSTRAINT health_wellbeing_records_pkey PRIMARY KEY (health_record_id),
  CONSTRAINT health_wellbeing_records_resident_id_fkey FOREIGN KEY (resident_id) REFERENCES public.residents(resident_id)
);
CREATE TABLE public.home_visitations (
  visitation_id integer NOT NULL,
  resident_id integer,
  visit_date date,
  social_worker text,
  visit_type text,
  location_visited text,
  family_members_present text,
  purpose text,
  observations text,
  family_cooperation_level text,
  safety_concerns_noted boolean DEFAULT false,
  follow_up_needed boolean DEFAULT false,
  follow_up_notes text,
  visit_outcome text,
  CONSTRAINT home_visitations_pkey PRIMARY KEY (visitation_id),
  CONSTRAINT home_visitations_resident_id_fkey FOREIGN KEY (resident_id) REFERENCES public.residents(resident_id)
);
CREATE TABLE public.in_kind_donation_items (
  item_id integer NOT NULL,
  donation_id integer,
  item_name text,
  item_category text,
  quantity numeric,
  unit_of_measure text,
  estimated_unit_value numeric,
  intended_use text,
  received_condition text,
  CONSTRAINT in_kind_donation_items_pkey PRIMARY KEY (item_id),
  CONSTRAINT in_kind_donation_items_donation_id_fkey FOREIGN KEY (donation_id) REFERENCES public.donations(donation_id)
);
CREATE TABLE public.incident_reports (
  incident_id integer NOT NULL,
  resident_id integer,
  safehouse_id integer,
  incident_date date,
  incident_type text,
  severity text,
  description text,
  response_taken text,
  resolved boolean DEFAULT false,
  resolution_date date,
  reported_by text,
  follow_up_required boolean DEFAULT false,
  CONSTRAINT incident_reports_pkey PRIMARY KEY (incident_id),
  CONSTRAINT incident_reports_resident_id_fkey FOREIGN KEY (resident_id) REFERENCES public.residents(resident_id),
  CONSTRAINT incident_reports_safehouse_id_fkey FOREIGN KEY (safehouse_id) REFERENCES public.safehouses(safehouse_id)
);
CREATE TABLE public.intervention_plans (
  plan_id integer NOT NULL,
  resident_id integer,
  plan_category text,
  plan_description text,
  services_provided text,
  target_value numeric,
  target_date date,
  status text,
  case_conference_date date,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT intervention_plans_pkey PRIMARY KEY (plan_id),
  CONSTRAINT intervention_plans_resident_id_fkey FOREIGN KEY (resident_id) REFERENCES public.residents(resident_id)
);
CREATE TABLE public.partner_assignments (
  assignment_id integer NOT NULL,
  partner_id integer,
  safehouse_id integer,
  program_area text,
  assignment_start date,
  assignment_end date,
  responsibility_notes text,
  is_primary boolean DEFAULT false,
  status text,
  CONSTRAINT partner_assignments_pkey PRIMARY KEY (assignment_id),
  CONSTRAINT partner_assignments_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.partners(partner_id),
  CONSTRAINT partner_assignments_safehouse_id_fkey FOREIGN KEY (safehouse_id) REFERENCES public.safehouses(safehouse_id)
);
CREATE TABLE public.partners (
  partner_id integer NOT NULL,
  partner_name text NOT NULL,
  partner_type text,
  role_type text,
  contact_name text,
  email text,
  phone text,
  region text,
  status text,
  start_date date,
  end_date date,
  notes text,
  CONSTRAINT partners_pkey PRIMARY KEY (partner_id)
);
CREATE TABLE public.process_recordings (
  recording_id integer NOT NULL,
  resident_id integer,
  session_date date,
  social_worker text,
  session_type text,
  session_duration_minutes integer,
  emotional_state_observed text,
  emotional_state_end text,
  session_narrative text,
  interventions_applied text,
  follow_up_actions text,
  progress_noted boolean DEFAULT false,
  concerns_flagged boolean DEFAULT false,
  referral_made boolean DEFAULT false,
  notes_restricted text,
  CONSTRAINT process_recordings_pkey PRIMARY KEY (recording_id),
  CONSTRAINT process_recordings_resident_id_fkey FOREIGN KEY (resident_id) REFERENCES public.residents(resident_id)
);
CREATE TABLE public.public_impact_snapshots (
  snapshot_id integer NOT NULL,
  snapshot_date date,
  headline text,
  summary_text text,
  metric_payload_json jsonb,
  is_published boolean DEFAULT false,
  published_at date,
  CONSTRAINT public_impact_snapshots_pkey PRIMARY KEY (snapshot_id)
);
CREATE TABLE public.resident_risk_scores (
  score_id integer NOT NULL DEFAULT nextval('resident_risk_scores_score_id_seq'::regclass),
  resident_id integer,
  scored_at timestamp with time zone DEFAULT now(),
  health_score_delta_6m numeric,
  stall_risk_probability numeric,
  incident_risk_probability numeric,
  risk_tier text,
  CONSTRAINT resident_risk_scores_pkey PRIMARY KEY (score_id),
  CONSTRAINT resident_risk_scores_resident_id_fkey FOREIGN KEY (resident_id) REFERENCES public.residents(resident_id)
);
CREATE TABLE public.residents (
  resident_id integer NOT NULL,
  case_control_no text,
  internal_code text,
  safehouse_id integer,
  case_status text,
  sex text,
  date_of_birth date,
  birth_status text,
  place_of_birth text,
  religion text,
  case_category text,
  sub_cat_orphaned boolean DEFAULT false,
  sub_cat_trafficked boolean DEFAULT false,
  sub_cat_child_labor boolean DEFAULT false,
  sub_cat_physical_abuse boolean DEFAULT false,
  sub_cat_sexual_abuse boolean DEFAULT false,
  sub_cat_osaec boolean DEFAULT false,
  sub_cat_cicl boolean DEFAULT false,
  sub_cat_at_risk boolean DEFAULT false,
  sub_cat_street_child boolean DEFAULT false,
  sub_cat_child_with_hiv boolean DEFAULT false,
  is_pwd boolean DEFAULT false,
  pwd_type text,
  has_special_needs boolean DEFAULT false,
  special_needs_diagnosis text,
  family_is_4ps boolean DEFAULT false,
  family_solo_parent boolean DEFAULT false,
  family_indigenous boolean DEFAULT false,
  family_parent_pwd boolean DEFAULT false,
  family_informal_settler boolean DEFAULT false,
  date_of_admission date,
  age_upon_admission text,
  present_age text,
  length_of_stay text,
  referral_source text,
  referring_agency_person text,
  date_colb_registered date,
  date_colb_obtained date,
  assigned_social_worker text,
  initial_case_assessment text,
  date_case_study_prepared date,
  reintegration_type text,
  reintegration_status text,
  initial_risk_level text,
  current_risk_level text,
  date_enrolled date,
  date_closed date,
  created_at timestamp with time zone DEFAULT now(),
  notes_restricted text,
  CONSTRAINT residents_pkey PRIMARY KEY (resident_id),
  CONSTRAINT residents_safehouse_id_fkey FOREIGN KEY (safehouse_id) REFERENCES public.safehouses(safehouse_id)
);
CREATE TABLE public.roles (
  id integer NOT NULL DEFAULT nextval('roles_id_seq'::regclass),
  name text NOT NULL UNIQUE,
  CONSTRAINT roles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.safehouse_monthly_metrics (
  metric_id integer NOT NULL,
  safehouse_id integer,
  month_start date,
  month_end date,
  active_residents integer,
  avg_education_progress numeric,
  avg_health_score numeric,
  process_recording_count integer DEFAULT 0,
  home_visitation_count integer DEFAULT 0,
  incident_count integer DEFAULT 0,
  notes text,
  CONSTRAINT safehouse_monthly_metrics_pkey PRIMARY KEY (metric_id),
  CONSTRAINT safehouse_monthly_metrics_safehouse_id_fkey FOREIGN KEY (safehouse_id) REFERENCES public.safehouses(safehouse_id)
);
CREATE TABLE public.safehouses (
  safehouse_id integer NOT NULL,
  safehouse_code text NOT NULL,
  name text NOT NULL,
  region text,
  city text,
  province text,
  country text DEFAULT 'Philippines'::text,
  open_date date,
  status text,
  capacity_girls integer,
  capacity_staff integer,
  current_occupancy integer,
  notes text,
  CONSTRAINT safehouses_pkey PRIMARY KEY (safehouse_id)
);
CREATE TABLE public.social_media_posts (
  post_id integer NOT NULL,
  platform text,
  platform_post_id text,
  post_url text,
  created_at timestamp with time zone,
  day_of_week text,
  post_hour smallint,
  post_type text,
  media_type text,
  caption text,
  hashtags text,
  num_hashtags smallint DEFAULT 0,
  mentions_count smallint DEFAULT 0,
  has_call_to_action boolean DEFAULT false,
  call_to_action_type text,
  content_topic text,
  sentiment_tone text,
  caption_length integer,
  features_resident_story boolean DEFAULT false,
  campaign_name text,
  is_boosted boolean DEFAULT false,
  boost_budget_php numeric,
  impressions integer,
  reach integer,
  likes integer,
  comments integer,
  shares integer,
  saves integer,
  click_throughs integer,
  video_views integer,
  engagement_rate numeric,
  profile_visits integer,
  donation_referrals integer,
  estimated_donation_value_php numeric,
  follower_count_at_post integer,
  watch_time_seconds numeric,
  avg_view_duration_seconds numeric,
  subscriber_count_at_post integer,
  forwards numeric,
  CONSTRAINT social_media_posts_pkey PRIMARY KEY (post_id)
);
CREATE TABLE public.supporters (
  supporter_id integer NOT NULL,
  supporter_type text,
  display_name text,
  organization_name text,
  first_name text,
  last_name text,
  relationship_type text,
  region text,
  country text,
  email text,
  phone text,
  status text,
  created_at date,
  first_donation_date date,
  acquisition_channel text,
  CONSTRAINT supporters_pkey PRIMARY KEY (supporter_id)
);
CREATE TABLE public.user_roles (
  user_id uuid NOT NULL,
  role_id integer NOT NULL,
  CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_id),
  CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT user_roles_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(id)
);