-- =============================================================================
-- Staff portal: case management RLS + insert defaults + safehouse occupancy sync
-- =============================================================================
-- Apply with Supabase CLI (from repo root):
--   npx supabase db push
--   # or
--   npx supabase migration up
--
-- Or pipe this file to `psql` against your project database.
--
-- Before running: confirm role IDs match public.roles and src/lib/roles.ts:
--   SELECT role_id, name FROM public.roles ORDER BY role_id;
-- Expect: staff = 3, admin = 4 (SOCIAL_MEDIA_REP = 1, DONOR = 2, USER = 5).
-- =============================================================================

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. Helper for policies (same pattern as SUPABASE_DONATIONS_SETUP.md §4)
-- ─────────────────────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.is_staff_portal_user()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.user_roles ur
    WHERE ur.user_id = auth.uid()
      AND ur.role_id IN (3, 4) -- staff, admin — adjust if your roles table differs
  );
$$;

REVOKE ALL ON FUNCTION public.is_staff_portal_user() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_staff_portal_user() TO authenticated;

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. Auto-increment IDs for portal inserts (where PK is plain integer, not IDENTITY)
-- ─────────────────────────────────────────────────────────────────────────────
-- Skip residents.resident_id: hosted Supabase often uses GENERATED BY DEFAULT AS IDENTITY,
-- which cannot take DEFAULT nextval(...). Omitting those lines avoids SQLSTATE 42601.

CREATE SEQUENCE IF NOT EXISTS public.process_recordings_recording_id_seq;
CREATE SEQUENCE IF NOT EXISTS public.home_visitations_visitation_id_seq;

SELECT setval(
  'public.process_recordings_recording_id_seq',
  COALESCE((SELECT MAX(recording_id) FROM public.process_recordings), 0)
);
SELECT setval(
  'public.home_visitations_visitation_id_seq',
  COALESCE((SELECT MAX(visitation_id) FROM public.home_visitations), 0)
);

ALTER TABLE public.process_recordings
  ALTER COLUMN recording_id SET DEFAULT nextval('public.process_recordings_recording_id_seq');
ALTER TABLE public.home_visitations
  ALTER COLUMN visitation_id SET DEFAULT nextval('public.home_visitations_visitation_id_seq');

ALTER SEQUENCE public.process_recordings_recording_id_seq OWNED BY public.process_recordings.recording_id;
ALTER SEQUENCE public.home_visitations_visitation_id_seq OWNED BY public.home_visitations.visitation_id;

GRANT USAGE, SELECT ON SEQUENCE public.process_recordings_recording_id_seq TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.home_visitations_visitation_id_seq TO authenticated;

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. Table privileges (RLS still restricts which rows apply)
-- ─────────────────────────────────────────────────────────────────────────────

GRANT SELECT, INSERT, UPDATE, DELETE ON public.residents TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.process_recordings TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.home_visitations TO authenticated;
GRANT SELECT ON public.safehouses TO authenticated;

-- ─────────────────────────────────────────────────────────────────────────────
-- 4. Row Level Security — staff/admin full CRUD on case-management tables
-- ─────────────────────────────────────────────────────────────────────────────

ALTER TABLE public.residents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.process_recordings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.home_visitations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS residents_staff_all ON public.residents;
CREATE POLICY residents_staff_all
  ON public.residents
  FOR ALL
  TO authenticated
  USING (public.is_staff_portal_user())
  WITH CHECK (public.is_staff_portal_user());

DROP POLICY IF EXISTS process_recordings_staff_all ON public.process_recordings;
CREATE POLICY process_recordings_staff_all
  ON public.process_recordings
  FOR ALL
  TO authenticated
  USING (public.is_staff_portal_user())
  WITH CHECK (public.is_staff_portal_user());

DROP POLICY IF EXISTS home_visitations_staff_all ON public.home_visitations;
CREATE POLICY home_visitations_staff_all
  ON public.home_visitations
  FOR ALL
  TO authenticated
  USING (public.is_staff_portal_user())
  WITH CHECK (public.is_staff_portal_user());

-- Optional: allow authenticated users to read safehouse names/capacity for dashboard UI.
-- (Portal dashboard queries safehouses; if you already have broader policies, this is redundant.)
DROP POLICY IF EXISTS safehouses_staff_select ON public.safehouses;
CREATE POLICY safehouses_staff_select
  ON public.safehouses
  FOR SELECT
  TO authenticated
  USING (public.is_staff_portal_user());

-- If safehouses had no RLS before, enable it so the SELECT policy takes effect.
ALTER TABLE public.safehouses ENABLE ROW LEVEL SECURITY;

-- ─────────────────────────────────────────────────────────────────────────────
-- 5. Keep safehouses.current_occupancy in sync with Active residents per house
-- ─────────────────────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.trg_residents_refresh_safehouse_occupancy()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    IF OLD.safehouse_id IS NOT NULL THEN
      UPDATE public.safehouses s
      SET current_occupancy = (
        SELECT COUNT(*)::int
        FROM public.residents r
        WHERE r.safehouse_id = OLD.safehouse_id
          AND r.case_status = 'Active'
      )
      WHERE s.safehouse_id = OLD.safehouse_id;
    END IF;
    RETURN OLD;
  END IF;

  IF TG_OP = 'UPDATE' THEN
    IF OLD.safehouse_id IS NOT NULL
       AND (
         OLD.safehouse_id IS DISTINCT FROM NEW.safehouse_id
         OR OLD.case_status IS DISTINCT FROM NEW.case_status
       )
    THEN
      UPDATE public.safehouses s
      SET current_occupancy = (
        SELECT COUNT(*)::int
        FROM public.residents r
        WHERE r.safehouse_id = OLD.safehouse_id
          AND r.case_status = 'Active'
      )
      WHERE s.safehouse_id = OLD.safehouse_id;
    END IF;
    IF NEW.safehouse_id IS NOT NULL
       AND (
         OLD.safehouse_id IS DISTINCT FROM NEW.safehouse_id
         OR OLD.case_status IS DISTINCT FROM NEW.case_status
       )
    THEN
      UPDATE public.safehouses s
      SET current_occupancy = (
        SELECT COUNT(*)::int
        FROM public.residents r
        WHERE r.safehouse_id = NEW.safehouse_id
          AND r.case_status = 'Active'
      )
      WHERE s.safehouse_id = NEW.safehouse_id;
    END IF;
    RETURN NEW;
  END IF;

  -- INSERT
  IF NEW.safehouse_id IS NOT NULL AND NEW.case_status = 'Active' THEN
    UPDATE public.safehouses s
    SET current_occupancy = (
      SELECT COUNT(*)::int
      FROM public.residents r
      WHERE r.safehouse_id = NEW.safehouse_id
        AND r.case_status = 'Active'
    )
    WHERE s.safehouse_id = NEW.safehouse_id;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS residents_refresh_safehouse_occupancy ON public.residents;
CREATE TRIGGER residents_refresh_safehouse_occupancy
  AFTER INSERT OR UPDATE OR DELETE ON public.residents
  FOR EACH ROW
  EXECUTE FUNCTION public.trg_residents_refresh_safehouse_occupancy();

-- One-time reconciliation (optional but helpful after first deploy)
UPDATE public.safehouses sh
SET current_occupancy = (
  SELECT COUNT(*)::int
  FROM public.residents r
  WHERE r.safehouse_id = sh.safehouse_id
    AND r.case_status = 'Active'
);
